### ISSUE TITLE
Add mmore languages

### ISSUE THREAD

**Issue by SajMoooner** [neurlang/goruut#1]
Please add languages

**Comment by neurlang** [comment]
added Italian

**Comment by neurlang** [comment]
added Luxembourgish

**Comment by neurlang** [comment]
added Dutch

**Comment by neurlang** [comment]
added Portuguese

**Comment by neurlang** [comment]
planned languages for the next release:
* vietnamese
* esperanto
* icelandic
* jamaican
* norwegian
* swahili
* tahitian
* finnish
* romanian
* japanese

**Comment by neurlang** [comment]
added Romanian, Finnish, Isan, Swahili, Esperanto, Icelandic, Norwegian, Jamaican

planned
* vietnamese
* japanese

not planned tahitian it was a confusion with Isan

**Comment by neurlang** [comment]
added japanese

**Comment by neurlang** [comment]
added vietnamese
